---
apiVersion: v1
kind: Template
labels:
  build: "${REPO_NAME}-app"
  template: "${REPO_NAME}-app-bc-template"
metadata:
  name: "${REPO_NAME}-app-bc"
objects:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: "${REPO_NAME}-app"
    spec:
      lookupPolicy:
        local: false
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      name: "${REPO_NAME}-app"
    spec:
      completionDeadlineSeconds: 600
      failedBuildsHistoryLimit: 3
      nodeSelector:
      output:
        to:
          kind: ImageStreamTag
          name: "${REPO_NAME}-app:latest"
      postCommit: {}
      resources:
        requests:
          cpu: 2000m
          memory: 1Gi
        limits:
          cpu: 4000m
          memory: 2Gi
      runPolicy: SerialLatestOnly
      source:
        contextDir: docker
        git:
          ref: "${SOURCE_REPO_REF}"
          uri: "${SOURCE_REPO_URL}"
        type: Git
      strategy:
        dockerStrategy:
          from:
            kind: DockerImage
            name: "${BASE_IMAGE}"
        type: Docker
      successfulBuildsHistoryLimit: 3
parameters:
  - name: BASE_IMAGE
    description: Base Image to build from
    displayName: Base Image
    required: true
    value: docker.io/python:3.11-alpine
  - name: REPO_NAME
    description: Application repository name
    displayName: Repository Name
    required: true
  - name: SOURCE_REPO_REF
    description: Git Pull Request Reference (i.e. 'pull/CHANGE_ID/head')
    displayName: Source Repository Reference
    required: true
  - name: SOURCE_REPO_URL
    description: Git Repository URL
    displayName: Source Repository URL
    required: true
